### ISSUE TITLE
Copyright infringement/license violation on this repository

### ISSUE THREAD

**Issue by kerkmann** [lpotthast/leptos-keycloak-auth#1]
I have two small things I would like to address. I think the [leptos-keycloak-auth](https://github.com/lpotthast/leptos-keycloak-auth) crate is great, it has many things implemented that I haven't. However, I have noticed two things that make me a little uncomfortable. I've seen this project use code from my crate [leptos_oidc](https://gitlab.com/kerkmann/leptos_oidc), but this project doesn't even reference my code. This clearly violates the MIT license and is not the purpose of the license. Also, this project is released under the Apache license without asking for permission to release my code, which is licensed under the MIT only. In itself, under normal condition I would agree to this, but I don't like the fact that it was not asked first and that the MIT license is completely violated.

Kind regards,

Daniél

**Comment by koopa1338** [comment]
In a quick comparison, it seems very sus to me to just copy the `response.rs` 1 to 1 and just remove the MIT license header. This doesn't align with the core principles of open source.

**Comment by kerkmann** [comment]
@koopa1338 yes, indeed a small list of copies:
- [response.rs](https://gitlab.com/kerkmann/leptos_oidc/-/blob/main/src/response.rs) entirely (everything with 124 Lines)
- [components.rs](https://gitlab.com/kerkmann/leptos_oidc/-/blob/main/src/components.rs) partially (one function with 24 lines)
- [error.rs](https://github.com/lpotthast/leptos-keycloak-auth/blob/main/src/error.rs) was "heavilly inspied", minor changes and copying the documentation.

**Comment by lpotthast** [comment]
Hi Daniél,

thanks for reaching out.
We might have different takes on this.

You are right, this library is inspired from your great work.
After looking at the available solution though, tinkering with it, 
noticing that it wouldn't cut it and knowing that I need a working solution quickly,
re-writing 80% of it, leaving only boilerplaty code behind (as you mentioned), 
adding 200% more code in terms of features (all roughly speaking)
and targeting a different audience (see below),
I decided to not keep this private and that it would be worth a separate crate.

If you want a solution whose abstraction level is, by name, raised to the oidc protocol / oauth2 level, 
maybe because you want to easily switch between auth provider implementations and want no library level lock in,
look no further than `leptos_oidc`.

If you are ok with a dependency specifically build for Keycloak, likely maintaining additional features from the official [keycloak.js](https://github.com/keycloak/keycloak/blob/main/js/libs/keycloak-js/src/keycloak.js) adapter in the future (making it inappropriate for other auth providers) `leptos-keycloak-auth` might be worth a look.

To maintaining file-level licensing information: I simply find that to be noisy, duplication and unreadable when developing.
Also, no commonly used license, including MIT, requires that to be done.

But you are right again, I should have mentioned your work from the start, no matter whats left of it.
And I will happily mention you in this project from here on after!
I never intended to offend you in any way and I am deeply sorry if I made you feel that way!

Cheers

**Comment by kerkmann** [comment]
Hi Lukas, first af all, thanks for your big answer. There are some pinpoints i would like to discuss comment, based on your answer.

> You are right, this library is inspired from your great work.
After looking at the available solution though, tinkering with it,
noticing that it wouldn't cut it and knowing that I need a working solution quickly,
re-writing 80% of it, leaving only boilerplate code behind (as you mentioned),
adding 200% more code in terms of features (all roughly speaking)
and targeting a different audience (see below),
I decided to not keep this private and that it would be worth a separate crate.

Maybe my words was a little bit harsh. I am happy for every solution. Especially for Keycloak (because I like the simplicity to just add one endpoint and everything is happening automatically under the hood). I did publish the crate `leptos_oidc` so everyone can copy from it and use it. I would not use an MIT licence if I would not like to be copied. The only thing is, violating the license (more on that later). ^^"

> If you are ok with a dependency specifically build for Keycloak, likely maintaining additional features from the official [keycloak.js](https://github.com/keycloak/keycloak/blob/main/js/libs/keycloak-js/src/keycloak.js) adapter in the future (making it inappropriate for other auth providers) leptos-keycloak-auth might be worth a look.

Would be awesome to see such a library in Rust! <3

> To maintaining file-level licensing information: I simply find that to be noisy, duplication and unreadable when developing.
Also, no commonly used license, including MIT, requires that to be done.

I think there are three parts which needs to be mentioned.

1) I understand that people are annoyed of such a big license banner at the beginning of the file. I totally understand that and that's a personal preference (for their own code). And that's something which isn't so important, at all.

2) I am a little bit allergic to not mention it at all. The MIT license has a paragraph called `The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.` and that's the part which was totally violated. I totally understand if there is no big banner. But you could also write a small text above the function which you are copying. For example:

```rust
// Copyright (c) 2023 Daniél Kerkmann <daniel@kerkmann.dev>
// Licensed under MIT
// See: https://gitlab.com/kerkmann/leptos_oidc
/// The doc string from the library
pub fn some_function_from_the_library {
    // Some stuff
}
```
Or
```rust

pub fn some_function_from_the_library{
   // Here is your code.
   ...
  // Here is code of the other person
  // Copyright (c) 2023 Daniél Kerkmann <daniel@kerkmann.dev>
  // Licensed under MIT
  // See: https://gitlab.com/kerkmann/leptos_oidc
  ...
  // Here is your code.
  ...
}
```

If you copy the entire file, just write this on top of your file, if you copy some functions, just write it above the function. Otherwise it's not clear, that this part is copyright from another person.

3) Also another problem is, currently I am the copyright owner of that code. I granted everyone the permission to use that code, under the MIT license. But, that means that it's only licensed under MIT. The problem besides not mentioning it, is re licensing  the code, which you are not allowed to do. If an open source project is made with multiple contributors under a specific license, then the contributor gave access to their code under that specific license. It's not allowed for the maintainer to just change the license for their personal opinion. The only solution for re licensing is "rewrite it completely differently, so it's your code and only your code", or "ask every contributor if it's okay for the person to license it under a different license". And that's something which also not happened. A small message or email with the text "hey is it okay if I license that code under the Apache 2 license?" and a grant from my side, would be enough. But not asking and doing it silently is something which is first of all forbidden and second of all, not really a nice thing to Open-Source contributors.

> But you are right again, I should have mentioned your work from the start, no matter whats left of it.
And I will happily mention you in this project from here on after!

Would be awesome, like i said, a small 2-3 line over the functions, would be enough. That's how the MIT license is intended. And that's something which should be done in the future every time. Whenever you see a good solution (for example StackOverflow), just write it above the code. Above the function if it's the entire function, or above a specific code section, if it's just this section. That's also helps you to ask the other contributors in the future by changing the license and is the bare minimum. ^^"

>  I never intended to offend you in any way and I am deeply sorry if I made you feel that way!

I totally understand that and hope my words were not too harsh. It was a combination of violating the MIT license AND re licensing my code without asking for permissions, which offended me a little bit. But I also don't think that this was your intention. ^^"

One last thing: Giving access to code (through MIT for example), doesn't mean that the person give up their copyright. That's that I mean with re licensing for the Apache 2 license. ;)
